name = "bdiptv-visitors"
main = "./visitor-counter-worker.js"
compatibility_date = "2026-02-25"

kv_namespaces = [
  { binding = "VISITORS", id = "5a0bb25940604531baa696261a2735d0" }
]

[vars]
ALLOWED_ORIGIN = "https://bdixtv.mhosen.com"
VISITOR_TTL_SECONDS = "180"